---

- name: Create network interfaces file
  hosts: '{{ target | default(all) }}'
  remote_user: root
  become: yes
  vars_files:
    - vars/vlan_network_mapping.yml 

  tasks:
  - name: make host ip static
    template:
      src: templates/interfaces.cfg.j2
      dest: /etc/network/interfaces
      owner: root
      group: root
      mode: 0644

  - name: Ensure files in interfaces.d are loaded
    lineinfile:
      dest: /etc/network/interfaces
      state: present
      line: 'source /etc/network/interfaces.d/*.cfg'
      insertafter: 'For more information'

  - name: Create os-refimpl-devices.cfg
    template:
      src: templates/os-refimpl-devices.cfg.j2
      dest: /etc/network/interfaces.d/os-refimpl-devices.cfg
      owner: root
      group: root
      mode: 0644

  - name: reboot servers
    shell: reboot
